// ملف البيانات الكامل - جميع العقود الـ 445
// يرجى استبدال هذه البيانات النموذجية ببياناتك الكاملة

const contractsData = [
  // الجامعة الإسلامية (3 عقود)
  {"university":"الجامعة الإسلامية","program":"الاقتصاد","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-03-07","endDate":"2025-03-06","management":"إدارة برامج العلوم الإنسانية والتربوية","progress":"40% - زيارة التحقق","docReceived":"تم التسليم متأخر","docDate":"2025-01-23","updatedDocReceived":"تم التسليم متأخر","updatedDocDate":"2025-05-15","visitScheduled":"تم جدولة الزيارة - متأخر","visitDate":"2026-01-25"},
  {"university":"الجامعة الإسلامية","program":"الإعلام والاتصال","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-03-07","endDate":"2025-03-06","management":"إدارة برامج العلوم الإنسانية والتربوية","progress":"40% - زيارة التحقق","docReceived":"تم التسليم متأخر","docDate":"2025-01-23","updatedDocReceived":"تم التسليم متأخر","updatedDocDate":"2025-08-31","visitScheduled":"تم جدولة الزيارة - متأخر","visitDate":"2026-02-01"},
  {"university":"الجامعة الإسلامية","program":"أصول التربية الإسلامية","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-03-07","endDate":"2025-03-06","management":"إدارة برامج العلوم الإنسانية والتربوية","progress":"40% - زيارة التحقق","docReceived":"تم التسليم متأخر","docDate":"2025-01-23","updatedDocReceived":"تم التسليم متأخر","updatedDocDate":"2025-04-13","visitScheduled":"تم جدولة الزيارة - متأخر","visitDate":"2025-11-30"},
  
  // جامعة الإمام عبد الرحمن بن فيصل (39 عقداً)
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في إدارة هندسة التشييد","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"التصميم الصناعي","degree":"بكالوريوس","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في الإدارة الهندسية","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في الهندسة البيئية","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في نظم المعلومات وتحليل البيانات","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العمارة","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الهندسية وعلوم الحاسب","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في جودة الرعاية الصحية وسلامة المرضى","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"40% - زيارة التحقق","docReceived":"تم التسليم متأخر","docDate":"2025-01-15","updatedDocReceived":"تم التسليم متأخر","updatedDocDate":"2025-06-05","visitScheduled":"لم تتم جدولة الزيارة","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"الصحة العامة","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في التقنية الحيوية","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"العلوم في تقنية متناهية الصغر","degree":"ماجستير","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"لم يتم التسليم","docDate":"","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"تقنية القلب","degree":"بكالوريوس","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"30% - العقود الجديدة - دراسة الوثائق","docReceived":"تم التسليم متأخر","docDate":"2025-08-14","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":"2026-01-25"},
  {"university":"جامعة الإمام عبد الرحمن بن فيصل","program":"الرعاية الطبية الطارئة","degree":"بكالوريوس","status":"تحت الإجراء","startDate":"2024-06-20","endDate":"2026-01-31","management":"إدارة برامج العلوم الصحية","progress":"5% - العقود الجديدة - اللقاء التعريفي","docReceived":"تم التسليم متأخر","docDate":"2025-10-15","updatedDocReceived":"لم يتم التسليم","updatedDocDate":"","visitScheduled":"","visitDate":""}
];

// ملاحظة: هذا الملف يحتوي على جزء صغير من البيانات كمثال
// للحصول على الوظائف الكاملة، يرجى إضافة جميع العقود الـ 445 هنا
// يمكنك نسخ البيانات من الملف الأصلي وتحويلها إلى تنسيق JSON

console.log(`Loaded ${contractsData.length} contracts`);
